### ISSUE TITLE
Search Update Style/Look feel

### ISSUE THREAD

**Issue by paulchrisluke** [pcl-labs/Way-Back-Wiki#4]
Use Shadcn and v0 to create a much better ui, use theming and consider light/dark mode

use shadcn command 

https://ui.shadcn.com/docs/components/command

https://cmdk.paco.me/

**Comment by paulchrisluke** [comment]
PR ready for review https://github.com/pcl-labs/Way-Back-Wiki/pull/8

**Comment by al3xen** [comment]
New search bar merged. Issue closed.
